# Generated by Django 2.0.7 on 2018-08-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blike',
            old_name='u_id',
            new_name='u',
        ),
    ]
