# Generated by Django 2.0.7 on 2018-08-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blike',
            name='u_id',
        ),
        migrations.DeleteModel(
            name='blike',
        ),
    ]
